### ISSUE TITLE
Update to pointycastle 2.0 broke things

### ISSUE THREAD

**Issue by fusion44** [anicdh/bip32-dart#8] opened 2021-02-12 06:10 UTC
Hi,

I have the following code: 
```dart
final mnemonic = bip39.generateMnemonic();
final seed = bip39.mnemonicToSeed(mnemonic);
final root = bip32.BIP32.fromSeed(seed); // error: Private key not in range [1, n] since pointycastle 2.0
```

Line three throws an error [Private key not in range [1, n]](https://github.com/dart-bitcoin/bip32-dart/blob/dbfd8d71d5693ed68bc5007ab608363c70656641/lib/src/bip32_base.dart#L217)

The same code seems to work well when overriding dependencies with an old pointycastle version:
```yaml
dependency_overrides:
  pointycastle: ^1.0.2
```

Thank you.

**Comment by willyfromtheblock** [comment] 2021-03-04 09:15
in my project downgrading crypto to 2.0.3  did the trick for some reason.

**Comment by redDwarf03** [comment] 2021-03-17 18:53
crypto is declared in BIP39 but not used so I don't think It was the reason of the fix. Fusion44, have you find a solution since 12 February ?

**Comment by redDwarf03** [comment] 2021-03-21 11:14
@fusion44 , have you find a solution please ? with flutter 2.0, we need to update all dependencies.

**Comment by fusion44** [comment] 2021-03-21 13:07
@redDwarf03 Unfortunately not. Currently working on another project but I eventually will get back to this one. So I'm still interested in a solution.

**Comment by redDwarf03** [comment] 2021-03-21 20:51
apparently, this is the method decodeBigInt the source of the issue
new code: https://github.com/bcgit/pc-dart/blob/be4142082f01cd3971bec4890342e039799c1f0e/lib/src/utils.dart#L19

```
/// Decode a BigInt from bytes in big-endian encoding.
/// Twos compliment.
BigInt decodeBigInt(List<int> bytes) {
  var negative = bytes.isNotEmpty && bytes[0] & 0x80 == 0x80;

  BigInt result;

  if (bytes.length == 1) {
    result = BigInt.from(bytes[0]);
  } else {
    result = BigInt.zero;
    for (var i = 0; i < bytes.length; i++) {
      var item = bytes[bytes.length - i - 1];
      result |= (BigInt.from(item) << (8 * i));
    }
  }
  return result != BigInt.zero
      ? negative ? result.toSigned(result.bitLength) : result
      : BigInt.zero;
}
```

old code:
```
BigInt decodeBigInt(List<int> bytes) {
  BigInt result = new BigInt.from(0);
  for (int i = 0; i < bytes.length; i++) {
    result += new BigInt.from(bytes[bytes.length - i - 1]) << (8 * i);
  }
  return result;
}
```

to be confirmed

**Comment by p3root** [comment] 2021-04-08 06:08
Should also be fixed with my PR!
https://github.com/dart-bitcoin/bip32-dart/pull/10

**Closed as completed** 2021-04-09 14:58 UTC
